# Sensor configuration: lb_ultrasonic_sensor (on Link_LBUltrasonicSensor)
# Generated automatically — edit this file to customize sensor parameters

type: sonar
link_name: Link_LBUltrasonicSensor
update_rate: 20
topic: /lb_ultrasonic/range
sonar:
  min: 0.25
  max: 4.5
  radius: 0.5236
