# Sensor configuration: lf_ultrasonic_sensor (on Link_LFUltrasonicSensor)
# Generated automatically — edit this file to customize sensor parameters

type: sonar
link_name: Link_LFUltrasonicSensor
update_rate: 20
topic: /lf_ultrasonic/range
sonar:
  min: 0.25
  max: 4.5
  radius: 0.5236
